<?php
$con=mysqli_connect('localhost','root','');
if(mysqli_connect_errno()){
	header('location:'.$_SERVER['"SERVER_NAME"'].'/shidagouwu');
	exit;
}
mysqli_set_charset($con,'utf8');
mysqli_select_db($con,'ahnu');
?>